// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data-layer.proto

package com.nobodyhub.datalayer.core.proto;

public final class DataLayerProtocol {
  private DataLayerProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code datalayer.model.StatusCode}
   */
  public enum StatusCode
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>OK = 0;</code>
     */
    OK(0),
    /**
     * <code>ERROR = 1;</code>
     */
    ERROR(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>OK = 0;</code>
     */
    public static final int OK_VALUE = 0;
    /**
     * <code>ERROR = 1;</code>
     */
    public static final int ERROR_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static StatusCode valueOf(int value) {
      return forNumber(value);
    }

    public static StatusCode forNumber(int value) {
      switch (value) {
        case 0: return OK;
        case 1: return ERROR;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<StatusCode>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        StatusCode> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<StatusCode>() {
            public StatusCode findValueByNumber(int number) {
              return StatusCode.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.nobodyhub.datalayer.core.proto.DataLayerProtocol.getDescriptor().getEnumTypes().get(0);
    }

    private static final StatusCode[] VALUES = values();

    public static StatusCode valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private StatusCode(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:datalayer.model.StatusCode)
  }

  /**
   * Protobuf enum {@code datalayer.model.OpType}
   */
  public enum OpType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>CREATE = 0;</code>
     */
    CREATE(0),
    /**
     * <code>READ = 1;</code>
     */
    READ(1),
    /**
     * <code>UPDATE = 2;</code>
     */
    UPDATE(2),
    /**
     * <code>DELETE = 3;</code>
     */
    DELETE(3),
    /**
     * <code>PERSIST = 4;</code>
     */
    PERSIST(4),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>CREATE = 0;</code>
     */
    public static final int CREATE_VALUE = 0;
    /**
     * <code>READ = 1;</code>
     */
    public static final int READ_VALUE = 1;
    /**
     * <code>UPDATE = 2;</code>
     */
    public static final int UPDATE_VALUE = 2;
    /**
     * <code>DELETE = 3;</code>
     */
    public static final int DELETE_VALUE = 3;
    /**
     * <code>PERSIST = 4;</code>
     */
    public static final int PERSIST_VALUE = 4;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static OpType valueOf(int value) {
      return forNumber(value);
    }

    public static OpType forNumber(int value) {
      switch (value) {
        case 0: return CREATE;
        case 1: return READ;
        case 2: return UPDATE;
        case 3: return DELETE;
        case 4: return PERSIST;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<OpType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        OpType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<OpType>() {
            public OpType findValueByNumber(int number) {
              return OpType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.nobodyhub.datalayer.core.proto.DataLayerProtocol.getDescriptor().getEnumTypes().get(1);
    }

    private static final OpType[] VALUES = values();

    public static OpType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private OpType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:datalayer.model.OpType)
  }

  public interface EntityOrBuilder extends
      // @@protoc_insertion_point(interface_extends:datalayer.model.Entity)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string entityClass = 1;</code>
     */
    java.lang.String getEntityClass();
    /**
     * <code>string entityClass = 1;</code>
     */
    com.google.protobuf.ByteString
        getEntityClassBytes();

    /**
     * <code>bytes entity = 2;</code>
     */
    com.google.protobuf.ByteString getEntity();
  }
  /**
   * <pre>
   * corresponds to a Java Persistence Entity
   * </pre>
   *
   * Protobuf type {@code datalayer.model.Entity}
   */
  public  static final class Entity extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:datalayer.model.Entity)
      EntityOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Entity.newBuilder() to construct.
    private Entity(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Entity() {
      entityClass_ = "";
      entity_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Entity(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              entityClass_ = s;
              break;
            }
            case 18: {

              entity_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.nobodyhub.datalayer.core.proto.DataLayerProtocol.internal_static_datalayer_model_Entity_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.nobodyhub.datalayer.core.proto.DataLayerProtocol.internal_static_datalayer_model_Entity_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Entity.class, com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Entity.Builder.class);
    }

    public static final int ENTITYCLASS_FIELD_NUMBER = 1;
    private volatile java.lang.Object entityClass_;
    /**
     * <code>string entityClass = 1;</code>
     */
    public java.lang.String getEntityClass() {
      java.lang.Object ref = entityClass_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        entityClass_ = s;
        return s;
      }
    }
    /**
     * <code>string entityClass = 1;</code>
     */
    public com.google.protobuf.ByteString
        getEntityClassBytes() {
      java.lang.Object ref = entityClass_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        entityClass_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ENTITY_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString entity_;
    /**
     * <code>bytes entity = 2;</code>
     */
    public com.google.protobuf.ByteString getEntity() {
      return entity_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getEntityClassBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, entityClass_);
      }
      if (!entity_.isEmpty()) {
        output.writeBytes(2, entity_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getEntityClassBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, entityClass_);
      }
      if (!entity_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, entity_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Entity)) {
        return super.equals(obj);
      }
      com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Entity other = (com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Entity) obj;

      boolean result = true;
      result = result && getEntityClass()
          .equals(other.getEntityClass());
      result = result && getEntity()
          .equals(other.getEntity());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ENTITYCLASS_FIELD_NUMBER;
      hash = (53 * hash) + getEntityClass().hashCode();
      hash = (37 * hash) + ENTITY_FIELD_NUMBER;
      hash = (53 * hash) + getEntity().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Entity parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Entity parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Entity parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Entity parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Entity parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Entity parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Entity parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Entity parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Entity parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Entity parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Entity parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Entity parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Entity prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * corresponds to a Java Persistence Entity
     * </pre>
     *
     * Protobuf type {@code datalayer.model.Entity}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:datalayer.model.Entity)
        com.nobodyhub.datalayer.core.proto.DataLayerProtocol.EntityOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.nobodyhub.datalayer.core.proto.DataLayerProtocol.internal_static_datalayer_model_Entity_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.nobodyhub.datalayer.core.proto.DataLayerProtocol.internal_static_datalayer_model_Entity_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Entity.class, com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Entity.Builder.class);
      }

      // Construct using com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Entity.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        entityClass_ = "";

        entity_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.nobodyhub.datalayer.core.proto.DataLayerProtocol.internal_static_datalayer_model_Entity_descriptor;
      }

      public com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Entity getDefaultInstanceForType() {
        return com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Entity.getDefaultInstance();
      }

      public com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Entity build() {
        com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Entity result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Entity buildPartial() {
        com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Entity result = new com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Entity(this);
        result.entityClass_ = entityClass_;
        result.entity_ = entity_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Entity) {
          return mergeFrom((com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Entity)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Entity other) {
        if (other == com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Entity.getDefaultInstance()) return this;
        if (!other.getEntityClass().isEmpty()) {
          entityClass_ = other.entityClass_;
          onChanged();
        }
        if (other.getEntity() != com.google.protobuf.ByteString.EMPTY) {
          setEntity(other.getEntity());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Entity parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Entity) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object entityClass_ = "";
      /**
       * <code>string entityClass = 1;</code>
       */
      public java.lang.String getEntityClass() {
        java.lang.Object ref = entityClass_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          entityClass_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string entityClass = 1;</code>
       */
      public com.google.protobuf.ByteString
          getEntityClassBytes() {
        java.lang.Object ref = entityClass_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          entityClass_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string entityClass = 1;</code>
       */
      public Builder setEntityClass(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        entityClass_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string entityClass = 1;</code>
       */
      public Builder clearEntityClass() {
        
        entityClass_ = getDefaultInstance().getEntityClass();
        onChanged();
        return this;
      }
      /**
       * <code>string entityClass = 1;</code>
       */
      public Builder setEntityClassBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        entityClass_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString entity_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes entity = 2;</code>
       */
      public com.google.protobuf.ByteString getEntity() {
        return entity_;
      }
      /**
       * <code>bytes entity = 2;</code>
       */
      public Builder setEntity(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        entity_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes entity = 2;</code>
       */
      public Builder clearEntity() {
        
        entity_ = getDefaultInstance().getEntity();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:datalayer.model.Entity)
    }

    // @@protoc_insertion_point(class_scope:datalayer.model.Entity)
    private static final com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Entity DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Entity();
    }

    public static com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Entity getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Entity>
        PARSER = new com.google.protobuf.AbstractParser<Entity>() {
      public Entity parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Entity(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Entity> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Entity> getParserForType() {
      return PARSER;
    }

    public com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Entity getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:datalayer.model.Response)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.datalayer.model.StatusCode statusCode = 1;</code>
     */
    int getStatusCodeValue();
    /**
     * <code>.datalayer.model.StatusCode statusCode = 1;</code>
     */
    com.nobodyhub.datalayer.core.proto.DataLayerProtocol.StatusCode getStatusCode();

    /**
     * <code>string message = 2;</code>
     */
    java.lang.String getMessage();
    /**
     * <code>string message = 2;</code>
     */
    com.google.protobuf.ByteString
        getMessageBytes();

    /**
     * <code>.datalayer.model.Entity entity = 3;</code>
     */
    boolean hasEntity();
    /**
     * <code>.datalayer.model.Entity entity = 3;</code>
     */
    com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Entity getEntity();
    /**
     * <code>.datalayer.model.Entity entity = 3;</code>
     */
    com.nobodyhub.datalayer.core.proto.DataLayerProtocol.EntityOrBuilder getEntityOrBuilder();
  }
  /**
   * <pre>
   * Response of the DB operation
   * </pre>
   *
   * Protobuf type {@code datalayer.model.Response}
   */
  public  static final class Response extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:datalayer.model.Response)
      ResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Response.newBuilder() to construct.
    private Response(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Response() {
      statusCode_ = 0;
      message_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Response(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              statusCode_ = rawValue;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              message_ = s;
              break;
            }
            case 26: {
              com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Entity.Builder subBuilder = null;
              if (entity_ != null) {
                subBuilder = entity_.toBuilder();
              }
              entity_ = input.readMessage(com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Entity.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(entity_);
                entity_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.nobodyhub.datalayer.core.proto.DataLayerProtocol.internal_static_datalayer_model_Response_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.nobodyhub.datalayer.core.proto.DataLayerProtocol.internal_static_datalayer_model_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Response.class, com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Response.Builder.class);
    }

    public static final int STATUSCODE_FIELD_NUMBER = 1;
    private int statusCode_;
    /**
     * <code>.datalayer.model.StatusCode statusCode = 1;</code>
     */
    public int getStatusCodeValue() {
      return statusCode_;
    }
    /**
     * <code>.datalayer.model.StatusCode statusCode = 1;</code>
     */
    public com.nobodyhub.datalayer.core.proto.DataLayerProtocol.StatusCode getStatusCode() {
      com.nobodyhub.datalayer.core.proto.DataLayerProtocol.StatusCode result = com.nobodyhub.datalayer.core.proto.DataLayerProtocol.StatusCode.valueOf(statusCode_);
      return result == null ? com.nobodyhub.datalayer.core.proto.DataLayerProtocol.StatusCode.UNRECOGNIZED : result;
    }

    public static final int MESSAGE_FIELD_NUMBER = 2;
    private volatile java.lang.Object message_;
    /**
     * <code>string message = 2;</code>
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <code>string message = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ENTITY_FIELD_NUMBER = 3;
    private com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Entity entity_;
    /**
     * <code>.datalayer.model.Entity entity = 3;</code>
     */
    public boolean hasEntity() {
      return entity_ != null;
    }
    /**
     * <code>.datalayer.model.Entity entity = 3;</code>
     */
    public com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Entity getEntity() {
      return entity_ == null ? com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Entity.getDefaultInstance() : entity_;
    }
    /**
     * <code>.datalayer.model.Entity entity = 3;</code>
     */
    public com.nobodyhub.datalayer.core.proto.DataLayerProtocol.EntityOrBuilder getEntityOrBuilder() {
      return getEntity();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (statusCode_ != com.nobodyhub.datalayer.core.proto.DataLayerProtocol.StatusCode.OK.getNumber()) {
        output.writeEnum(1, statusCode_);
      }
      if (!getMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, message_);
      }
      if (entity_ != null) {
        output.writeMessage(3, getEntity());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (statusCode_ != com.nobodyhub.datalayer.core.proto.DataLayerProtocol.StatusCode.OK.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, statusCode_);
      }
      if (!getMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, message_);
      }
      if (entity_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getEntity());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Response)) {
        return super.equals(obj);
      }
      com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Response other = (com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Response) obj;

      boolean result = true;
      result = result && statusCode_ == other.statusCode_;
      result = result && getMessage()
          .equals(other.getMessage());
      result = result && (hasEntity() == other.hasEntity());
      if (hasEntity()) {
        result = result && getEntity()
            .equals(other.getEntity());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STATUSCODE_FIELD_NUMBER;
      hash = (53 * hash) + statusCode_;
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      if (hasEntity()) {
        hash = (37 * hash) + ENTITY_FIELD_NUMBER;
        hash = (53 * hash) + getEntity().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Response parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Response parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Response prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Response of the DB operation
     * </pre>
     *
     * Protobuf type {@code datalayer.model.Response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:datalayer.model.Response)
        com.nobodyhub.datalayer.core.proto.DataLayerProtocol.ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.nobodyhub.datalayer.core.proto.DataLayerProtocol.internal_static_datalayer_model_Response_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.nobodyhub.datalayer.core.proto.DataLayerProtocol.internal_static_datalayer_model_Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Response.class, com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Response.Builder.class);
      }

      // Construct using com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        statusCode_ = 0;

        message_ = "";

        if (entityBuilder_ == null) {
          entity_ = null;
        } else {
          entity_ = null;
          entityBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.nobodyhub.datalayer.core.proto.DataLayerProtocol.internal_static_datalayer_model_Response_descriptor;
      }

      public com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Response getDefaultInstanceForType() {
        return com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Response.getDefaultInstance();
      }

      public com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Response build() {
        com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Response buildPartial() {
        com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Response result = new com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Response(this);
        result.statusCode_ = statusCode_;
        result.message_ = message_;
        if (entityBuilder_ == null) {
          result.entity_ = entity_;
        } else {
          result.entity_ = entityBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Response) {
          return mergeFrom((com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Response other) {
        if (other == com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Response.getDefaultInstance()) return this;
        if (other.statusCode_ != 0) {
          setStatusCodeValue(other.getStatusCodeValue());
        }
        if (!other.getMessage().isEmpty()) {
          message_ = other.message_;
          onChanged();
        }
        if (other.hasEntity()) {
          mergeEntity(other.getEntity());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Response parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Response) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int statusCode_ = 0;
      /**
       * <code>.datalayer.model.StatusCode statusCode = 1;</code>
       */
      public int getStatusCodeValue() {
        return statusCode_;
      }
      /**
       * <code>.datalayer.model.StatusCode statusCode = 1;</code>
       */
      public Builder setStatusCodeValue(int value) {
        statusCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.datalayer.model.StatusCode statusCode = 1;</code>
       */
      public com.nobodyhub.datalayer.core.proto.DataLayerProtocol.StatusCode getStatusCode() {
        com.nobodyhub.datalayer.core.proto.DataLayerProtocol.StatusCode result = com.nobodyhub.datalayer.core.proto.DataLayerProtocol.StatusCode.valueOf(statusCode_);
        return result == null ? com.nobodyhub.datalayer.core.proto.DataLayerProtocol.StatusCode.UNRECOGNIZED : result;
      }
      /**
       * <code>.datalayer.model.StatusCode statusCode = 1;</code>
       */
      public Builder setStatusCode(com.nobodyhub.datalayer.core.proto.DataLayerProtocol.StatusCode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        statusCode_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.datalayer.model.StatusCode statusCode = 1;</code>
       */
      public Builder clearStatusCode() {
        
        statusCode_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object message_ = "";
      /**
       * <code>string message = 2;</code>
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string message = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string message = 2;</code>
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string message = 2;</code>
       */
      public Builder clearMessage() {
        
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <code>string message = 2;</code>
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        message_ = value;
        onChanged();
        return this;
      }

      private com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Entity entity_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Entity, com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Entity.Builder, com.nobodyhub.datalayer.core.proto.DataLayerProtocol.EntityOrBuilder> entityBuilder_;
      /**
       * <code>.datalayer.model.Entity entity = 3;</code>
       */
      public boolean hasEntity() {
        return entityBuilder_ != null || entity_ != null;
      }
      /**
       * <code>.datalayer.model.Entity entity = 3;</code>
       */
      public com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Entity getEntity() {
        if (entityBuilder_ == null) {
          return entity_ == null ? com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Entity.getDefaultInstance() : entity_;
        } else {
          return entityBuilder_.getMessage();
        }
      }
      /**
       * <code>.datalayer.model.Entity entity = 3;</code>
       */
      public Builder setEntity(com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Entity value) {
        if (entityBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          entity_ = value;
          onChanged();
        } else {
          entityBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.datalayer.model.Entity entity = 3;</code>
       */
      public Builder setEntity(
          com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Entity.Builder builderForValue) {
        if (entityBuilder_ == null) {
          entity_ = builderForValue.build();
          onChanged();
        } else {
          entityBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.datalayer.model.Entity entity = 3;</code>
       */
      public Builder mergeEntity(com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Entity value) {
        if (entityBuilder_ == null) {
          if (entity_ != null) {
            entity_ =
              com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Entity.newBuilder(entity_).mergeFrom(value).buildPartial();
          } else {
            entity_ = value;
          }
          onChanged();
        } else {
          entityBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.datalayer.model.Entity entity = 3;</code>
       */
      public Builder clearEntity() {
        if (entityBuilder_ == null) {
          entity_ = null;
          onChanged();
        } else {
          entity_ = null;
          entityBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.datalayer.model.Entity entity = 3;</code>
       */
      public com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Entity.Builder getEntityBuilder() {
        
        onChanged();
        return getEntityFieldBuilder().getBuilder();
      }
      /**
       * <code>.datalayer.model.Entity entity = 3;</code>
       */
      public com.nobodyhub.datalayer.core.proto.DataLayerProtocol.EntityOrBuilder getEntityOrBuilder() {
        if (entityBuilder_ != null) {
          return entityBuilder_.getMessageOrBuilder();
        } else {
          return entity_ == null ?
              com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Entity.getDefaultInstance() : entity_;
        }
      }
      /**
       * <code>.datalayer.model.Entity entity = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Entity, com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Entity.Builder, com.nobodyhub.datalayer.core.proto.DataLayerProtocol.EntityOrBuilder> 
          getEntityFieldBuilder() {
        if (entityBuilder_ == null) {
          entityBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Entity, com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Entity.Builder, com.nobodyhub.datalayer.core.proto.DataLayerProtocol.EntityOrBuilder>(
                  getEntity(),
                  getParentForChildren(),
                  isClean());
          entity_ = null;
        }
        return entityBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:datalayer.model.Response)
    }

    // @@protoc_insertion_point(class_scope:datalayer.model.Response)
    private static final com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Response DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Response();
    }

    public static com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Response getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Response>
        PARSER = new com.google.protobuf.AbstractParser<Response>() {
      public Response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Response(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Response> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Response> getParserForType() {
      return PARSER;
    }

    public com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Response getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:datalayer.model.Request)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.datalayer.model.OpType opType = 1;</code>
     */
    int getOpTypeValue();
    /**
     * <code>.datalayer.model.OpType opType = 1;</code>
     */
    com.nobodyhub.datalayer.core.proto.DataLayerProtocol.OpType getOpType();

    /**
     * <code>.datalayer.model.Entity entity = 2;</code>
     */
    boolean hasEntity();
    /**
     * <code>.datalayer.model.Entity entity = 2;</code>
     */
    com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Entity getEntity();
    /**
     * <code>.datalayer.model.Entity entity = 2;</code>
     */
    com.nobodyhub.datalayer.core.proto.DataLayerProtocol.EntityOrBuilder getEntityOrBuilder();

    /**
     * <code>.datalayer.model.Entity criteria = 3;</code>
     */
    boolean hasCriteria();
    /**
     * <code>.datalayer.model.Entity criteria = 3;</code>
     */
    com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Entity getCriteria();
    /**
     * <code>.datalayer.model.Entity criteria = 3;</code>
     */
    com.nobodyhub.datalayer.core.proto.DataLayerProtocol.EntityOrBuilder getCriteriaOrBuilder();
  }
  /**
   * <pre>
   * Request made to execute DB operation.
   * 1. all operations will be executed in sequence in order of received
   * 2. operation sent in the same stream will be executed in the same transaction
   * 3. if the last operation is a OpType.READ/CREATE, the result of it will be send back via Response.Entity
   * </pre>
   *
   * Protobuf type {@code datalayer.model.Request}
   */
  public  static final class Request extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:datalayer.model.Request)
      RequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Request.newBuilder() to construct.
    private Request(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Request() {
      opType_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Request(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              opType_ = rawValue;
              break;
            }
            case 18: {
              com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Entity.Builder subBuilder = null;
              if (entity_ != null) {
                subBuilder = entity_.toBuilder();
              }
              entity_ = input.readMessage(com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Entity.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(entity_);
                entity_ = subBuilder.buildPartial();
              }

              break;
            }
            case 26: {
              com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Entity.Builder subBuilder = null;
              if (criteria_ != null) {
                subBuilder = criteria_.toBuilder();
              }
              criteria_ = input.readMessage(com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Entity.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(criteria_);
                criteria_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.nobodyhub.datalayer.core.proto.DataLayerProtocol.internal_static_datalayer_model_Request_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.nobodyhub.datalayer.core.proto.DataLayerProtocol.internal_static_datalayer_model_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Request.class, com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Request.Builder.class);
    }

    public static final int OPTYPE_FIELD_NUMBER = 1;
    private int opType_;
    /**
     * <code>.datalayer.model.OpType opType = 1;</code>
     */
    public int getOpTypeValue() {
      return opType_;
    }
    /**
     * <code>.datalayer.model.OpType opType = 1;</code>
     */
    public com.nobodyhub.datalayer.core.proto.DataLayerProtocol.OpType getOpType() {
      com.nobodyhub.datalayer.core.proto.DataLayerProtocol.OpType result = com.nobodyhub.datalayer.core.proto.DataLayerProtocol.OpType.valueOf(opType_);
      return result == null ? com.nobodyhub.datalayer.core.proto.DataLayerProtocol.OpType.UNRECOGNIZED : result;
    }

    public static final int ENTITY_FIELD_NUMBER = 2;
    private com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Entity entity_;
    /**
     * <code>.datalayer.model.Entity entity = 2;</code>
     */
    public boolean hasEntity() {
      return entity_ != null;
    }
    /**
     * <code>.datalayer.model.Entity entity = 2;</code>
     */
    public com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Entity getEntity() {
      return entity_ == null ? com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Entity.getDefaultInstance() : entity_;
    }
    /**
     * <code>.datalayer.model.Entity entity = 2;</code>
     */
    public com.nobodyhub.datalayer.core.proto.DataLayerProtocol.EntityOrBuilder getEntityOrBuilder() {
      return getEntity();
    }

    public static final int CRITERIA_FIELD_NUMBER = 3;
    private com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Entity criteria_;
    /**
     * <code>.datalayer.model.Entity criteria = 3;</code>
     */
    public boolean hasCriteria() {
      return criteria_ != null;
    }
    /**
     * <code>.datalayer.model.Entity criteria = 3;</code>
     */
    public com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Entity getCriteria() {
      return criteria_ == null ? com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Entity.getDefaultInstance() : criteria_;
    }
    /**
     * <code>.datalayer.model.Entity criteria = 3;</code>
     */
    public com.nobodyhub.datalayer.core.proto.DataLayerProtocol.EntityOrBuilder getCriteriaOrBuilder() {
      return getCriteria();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (opType_ != com.nobodyhub.datalayer.core.proto.DataLayerProtocol.OpType.CREATE.getNumber()) {
        output.writeEnum(1, opType_);
      }
      if (entity_ != null) {
        output.writeMessage(2, getEntity());
      }
      if (criteria_ != null) {
        output.writeMessage(3, getCriteria());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (opType_ != com.nobodyhub.datalayer.core.proto.DataLayerProtocol.OpType.CREATE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, opType_);
      }
      if (entity_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getEntity());
      }
      if (criteria_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getCriteria());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Request)) {
        return super.equals(obj);
      }
      com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Request other = (com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Request) obj;

      boolean result = true;
      result = result && opType_ == other.opType_;
      result = result && (hasEntity() == other.hasEntity());
      if (hasEntity()) {
        result = result && getEntity()
            .equals(other.getEntity());
      }
      result = result && (hasCriteria() == other.hasCriteria());
      if (hasCriteria()) {
        result = result && getCriteria()
            .equals(other.getCriteria());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + OPTYPE_FIELD_NUMBER;
      hash = (53 * hash) + opType_;
      if (hasEntity()) {
        hash = (37 * hash) + ENTITY_FIELD_NUMBER;
        hash = (53 * hash) + getEntity().hashCode();
      }
      if (hasCriteria()) {
        hash = (37 * hash) + CRITERIA_FIELD_NUMBER;
        hash = (53 * hash) + getCriteria().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Request parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Request parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Request prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Request made to execute DB operation.
     * 1. all operations will be executed in sequence in order of received
     * 2. operation sent in the same stream will be executed in the same transaction
     * 3. if the last operation is a OpType.READ/CREATE, the result of it will be send back via Response.Entity
     * </pre>
     *
     * Protobuf type {@code datalayer.model.Request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:datalayer.model.Request)
        com.nobodyhub.datalayer.core.proto.DataLayerProtocol.RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.nobodyhub.datalayer.core.proto.DataLayerProtocol.internal_static_datalayer_model_Request_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.nobodyhub.datalayer.core.proto.DataLayerProtocol.internal_static_datalayer_model_Request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Request.class, com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Request.Builder.class);
      }

      // Construct using com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        opType_ = 0;

        if (entityBuilder_ == null) {
          entity_ = null;
        } else {
          entity_ = null;
          entityBuilder_ = null;
        }
        if (criteriaBuilder_ == null) {
          criteria_ = null;
        } else {
          criteria_ = null;
          criteriaBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.nobodyhub.datalayer.core.proto.DataLayerProtocol.internal_static_datalayer_model_Request_descriptor;
      }

      public com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Request getDefaultInstanceForType() {
        return com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Request.getDefaultInstance();
      }

      public com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Request build() {
        com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Request buildPartial() {
        com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Request result = new com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Request(this);
        result.opType_ = opType_;
        if (entityBuilder_ == null) {
          result.entity_ = entity_;
        } else {
          result.entity_ = entityBuilder_.build();
        }
        if (criteriaBuilder_ == null) {
          result.criteria_ = criteria_;
        } else {
          result.criteria_ = criteriaBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Request) {
          return mergeFrom((com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Request other) {
        if (other == com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Request.getDefaultInstance()) return this;
        if (other.opType_ != 0) {
          setOpTypeValue(other.getOpTypeValue());
        }
        if (other.hasEntity()) {
          mergeEntity(other.getEntity());
        }
        if (other.hasCriteria()) {
          mergeCriteria(other.getCriteria());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Request parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Request) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int opType_ = 0;
      /**
       * <code>.datalayer.model.OpType opType = 1;</code>
       */
      public int getOpTypeValue() {
        return opType_;
      }
      /**
       * <code>.datalayer.model.OpType opType = 1;</code>
       */
      public Builder setOpTypeValue(int value) {
        opType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.datalayer.model.OpType opType = 1;</code>
       */
      public com.nobodyhub.datalayer.core.proto.DataLayerProtocol.OpType getOpType() {
        com.nobodyhub.datalayer.core.proto.DataLayerProtocol.OpType result = com.nobodyhub.datalayer.core.proto.DataLayerProtocol.OpType.valueOf(opType_);
        return result == null ? com.nobodyhub.datalayer.core.proto.DataLayerProtocol.OpType.UNRECOGNIZED : result;
      }
      /**
       * <code>.datalayer.model.OpType opType = 1;</code>
       */
      public Builder setOpType(com.nobodyhub.datalayer.core.proto.DataLayerProtocol.OpType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        opType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.datalayer.model.OpType opType = 1;</code>
       */
      public Builder clearOpType() {
        
        opType_ = 0;
        onChanged();
        return this;
      }

      private com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Entity entity_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Entity, com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Entity.Builder, com.nobodyhub.datalayer.core.proto.DataLayerProtocol.EntityOrBuilder> entityBuilder_;
      /**
       * <code>.datalayer.model.Entity entity = 2;</code>
       */
      public boolean hasEntity() {
        return entityBuilder_ != null || entity_ != null;
      }
      /**
       * <code>.datalayer.model.Entity entity = 2;</code>
       */
      public com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Entity getEntity() {
        if (entityBuilder_ == null) {
          return entity_ == null ? com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Entity.getDefaultInstance() : entity_;
        } else {
          return entityBuilder_.getMessage();
        }
      }
      /**
       * <code>.datalayer.model.Entity entity = 2;</code>
       */
      public Builder setEntity(com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Entity value) {
        if (entityBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          entity_ = value;
          onChanged();
        } else {
          entityBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.datalayer.model.Entity entity = 2;</code>
       */
      public Builder setEntity(
          com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Entity.Builder builderForValue) {
        if (entityBuilder_ == null) {
          entity_ = builderForValue.build();
          onChanged();
        } else {
          entityBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.datalayer.model.Entity entity = 2;</code>
       */
      public Builder mergeEntity(com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Entity value) {
        if (entityBuilder_ == null) {
          if (entity_ != null) {
            entity_ =
              com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Entity.newBuilder(entity_).mergeFrom(value).buildPartial();
          } else {
            entity_ = value;
          }
          onChanged();
        } else {
          entityBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.datalayer.model.Entity entity = 2;</code>
       */
      public Builder clearEntity() {
        if (entityBuilder_ == null) {
          entity_ = null;
          onChanged();
        } else {
          entity_ = null;
          entityBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.datalayer.model.Entity entity = 2;</code>
       */
      public com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Entity.Builder getEntityBuilder() {
        
        onChanged();
        return getEntityFieldBuilder().getBuilder();
      }
      /**
       * <code>.datalayer.model.Entity entity = 2;</code>
       */
      public com.nobodyhub.datalayer.core.proto.DataLayerProtocol.EntityOrBuilder getEntityOrBuilder() {
        if (entityBuilder_ != null) {
          return entityBuilder_.getMessageOrBuilder();
        } else {
          return entity_ == null ?
              com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Entity.getDefaultInstance() : entity_;
        }
      }
      /**
       * <code>.datalayer.model.Entity entity = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Entity, com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Entity.Builder, com.nobodyhub.datalayer.core.proto.DataLayerProtocol.EntityOrBuilder> 
          getEntityFieldBuilder() {
        if (entityBuilder_ == null) {
          entityBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Entity, com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Entity.Builder, com.nobodyhub.datalayer.core.proto.DataLayerProtocol.EntityOrBuilder>(
                  getEntity(),
                  getParentForChildren(),
                  isClean());
          entity_ = null;
        }
        return entityBuilder_;
      }

      private com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Entity criteria_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Entity, com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Entity.Builder, com.nobodyhub.datalayer.core.proto.DataLayerProtocol.EntityOrBuilder> criteriaBuilder_;
      /**
       * <code>.datalayer.model.Entity criteria = 3;</code>
       */
      public boolean hasCriteria() {
        return criteriaBuilder_ != null || criteria_ != null;
      }
      /**
       * <code>.datalayer.model.Entity criteria = 3;</code>
       */
      public com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Entity getCriteria() {
        if (criteriaBuilder_ == null) {
          return criteria_ == null ? com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Entity.getDefaultInstance() : criteria_;
        } else {
          return criteriaBuilder_.getMessage();
        }
      }
      /**
       * <code>.datalayer.model.Entity criteria = 3;</code>
       */
      public Builder setCriteria(com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Entity value) {
        if (criteriaBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          criteria_ = value;
          onChanged();
        } else {
          criteriaBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.datalayer.model.Entity criteria = 3;</code>
       */
      public Builder setCriteria(
          com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Entity.Builder builderForValue) {
        if (criteriaBuilder_ == null) {
          criteria_ = builderForValue.build();
          onChanged();
        } else {
          criteriaBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.datalayer.model.Entity criteria = 3;</code>
       */
      public Builder mergeCriteria(com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Entity value) {
        if (criteriaBuilder_ == null) {
          if (criteria_ != null) {
            criteria_ =
              com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Entity.newBuilder(criteria_).mergeFrom(value).buildPartial();
          } else {
            criteria_ = value;
          }
          onChanged();
        } else {
          criteriaBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.datalayer.model.Entity criteria = 3;</code>
       */
      public Builder clearCriteria() {
        if (criteriaBuilder_ == null) {
          criteria_ = null;
          onChanged();
        } else {
          criteria_ = null;
          criteriaBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.datalayer.model.Entity criteria = 3;</code>
       */
      public com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Entity.Builder getCriteriaBuilder() {
        
        onChanged();
        return getCriteriaFieldBuilder().getBuilder();
      }
      /**
       * <code>.datalayer.model.Entity criteria = 3;</code>
       */
      public com.nobodyhub.datalayer.core.proto.DataLayerProtocol.EntityOrBuilder getCriteriaOrBuilder() {
        if (criteriaBuilder_ != null) {
          return criteriaBuilder_.getMessageOrBuilder();
        } else {
          return criteria_ == null ?
              com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Entity.getDefaultInstance() : criteria_;
        }
      }
      /**
       * <code>.datalayer.model.Entity criteria = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Entity, com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Entity.Builder, com.nobodyhub.datalayer.core.proto.DataLayerProtocol.EntityOrBuilder> 
          getCriteriaFieldBuilder() {
        if (criteriaBuilder_ == null) {
          criteriaBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Entity, com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Entity.Builder, com.nobodyhub.datalayer.core.proto.DataLayerProtocol.EntityOrBuilder>(
                  getCriteria(),
                  getParentForChildren(),
                  isClean());
          criteria_ = null;
        }
        return criteriaBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:datalayer.model.Request)
    }

    // @@protoc_insertion_point(class_scope:datalayer.model.Request)
    private static final com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Request DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Request();
    }

    public static com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Request getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Request>
        PARSER = new com.google.protobuf.AbstractParser<Request>() {
      public Request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Request(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Request> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Request> getParserForType() {
      return PARSER;
    }

    public com.nobodyhub.datalayer.core.proto.DataLayerProtocol.Request getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_datalayer_model_Entity_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_datalayer_model_Entity_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_datalayer_model_Response_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_datalayer_model_Response_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_datalayer_model_Request_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_datalayer_model_Request_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020data-layer.proto\022\017datalayer.model\"-\n\006E" +
      "ntity\022\023\n\013entityClass\030\001 \001(\t\022\016\n\006entity\030\002 \001" +
      "(\014\"u\n\010Response\022/\n\nstatusCode\030\001 \001(\0162\033.dat" +
      "alayer.model.StatusCode\022\017\n\007message\030\002 \001(\t" +
      "\022\'\n\006entity\030\003 \001(\0132\027.datalayer.model.Entit" +
      "y\"\206\001\n\007Request\022\'\n\006opType\030\001 \001(\0162\027.datalaye" +
      "r.model.OpType\022\'\n\006entity\030\002 \001(\0132\027.datalay" +
      "er.model.Entity\022)\n\010criteria\030\003 \001(\0132\027.data" +
      "layer.model.Entity*\037\n\nStatusCode\022\006\n\002OK\020\000" +
      "\022\t\n\005ERROR\020\001*C\n\006OpType\022\n\n\006CREATE\020\000\022\010\n\004REA" +
      "D\020\001\022\n\n\006UPDATE\020\002\022\n\n\006DELETE\020\003\022\013\n\007PERSIST\020\004" +
      "2\224\001\n\020DataLayerService\022@\n\007execute\022\030.datal" +
      "ayer.model.Request\032\031.datalayer.model.Res" +
      "ponse(\001\022>\n\005query\022\030.datalayer.model.Reque" +
      "st\032\031.datalayer.model.Response0\001B7\n\"com.n" +
      "obodyhub.datalayer.core.protoB\021DataLayer" +
      "Protocolb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_datalayer_model_Entity_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_datalayer_model_Entity_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_datalayer_model_Entity_descriptor,
        new java.lang.String[] { "EntityClass", "Entity", });
    internal_static_datalayer_model_Response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_datalayer_model_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_datalayer_model_Response_descriptor,
        new java.lang.String[] { "StatusCode", "Message", "Entity", });
    internal_static_datalayer_model_Request_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_datalayer_model_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_datalayer_model_Request_descriptor,
        new java.lang.String[] { "OpType", "Entity", "Criteria", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
