// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data-layer.proto

package com.nobodyhub.datalayer.core.model;

public final class DataLayerProtocol {
    private DataLayerProtocol() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    /**
     * Protobuf enum {@code datalayer.model.OpType}
     */
    public enum OpType
            implements com.google.protobuf.ProtocolMessageEnum {
        /**
         * <code>CREATE = 0;</code>
         */
        CREATE(0),
        /**
         * <code>RRED = 1;</code>
         */
        RRED(1),
        /**
         * <code>UPDATE = 2;</code>
         */
        UPDATE(2),
        /**
         * <code>DELETE = 3;</code>
         */
        DELETE(3),
        UNRECOGNIZED(-1),;

        /**
         * <code>CREATE = 0;</code>
         */
        public static final int CREATE_VALUE = 0;
        /**
         * <code>RRED = 1;</code>
         */
        public static final int RRED_VALUE = 1;
        /**
         * <code>UPDATE = 2;</code>
         */
        public static final int UPDATE_VALUE = 2;
        /**
         * <code>DELETE = 3;</code>
         */
        public static final int DELETE_VALUE = 3;


        public final int getNumber() {
            if (this == UNRECOGNIZED) {
                throw new java.lang.IllegalArgumentException(
                        "Can't get the number of an unknown enum value.");
            }
            return value;
        }

        /**
         * @deprecated Use {@link #forNumber(int)} instead.
         */
        @java.lang.Deprecated
        public static OpType valueOf(int value) {
            return forNumber(value);
        }

        public static OpType forNumber(int value) {
            switch (value) {
                case 0:
                    return CREATE;
                case 1:
                    return RRED;
                case 2:
                    return UPDATE;
                case 3:
                    return DELETE;
                default:
                    return null;
            }
        }

        public static com.google.protobuf.Internal.EnumLiteMap<OpType>
        internalGetValueMap() {
            return internalValueMap;
        }

        private static final com.google.protobuf.Internal.EnumLiteMap<
                OpType> internalValueMap =
                new com.google.protobuf.Internal.EnumLiteMap<OpType>() {
                    public OpType findValueByNumber(int number) {
                        return OpType.forNumber(number);
                    }
                };

        public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
            return getDescriptor().getValues().get(ordinal());
        }

        public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
            return getDescriptor();
        }

        public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
            return DataLayerProtocol.getDescriptor().getEnumTypes().get(0);
        }

        private static final OpType[] VALUES = values();

        public static OpType valueOf(
                com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
            if (desc.getType() != getDescriptor()) {
                throw new java.lang.IllegalArgumentException(
                        "EnumValueDescriptor is not for this type.");
            }
            if (desc.getIndex() == -1) {
                return UNRECOGNIZED;
            }
            return VALUES[desc.getIndex()];
        }

        private final int value;

        private OpType(int value) {
            this.value = value;
        }

        // @@protoc_insertion_point(enum_scope:datalayer.model.OpType)
    }

    public interface EntityOrBuilder extends
            // @@protoc_insertion_point(interface_extends:datalayer.model.Entity)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>string entityClass = 1;</code>
         */
        java.lang.String getEntityClass();

        /**
         * <code>string entityClass = 1;</code>
         */
        com.google.protobuf.ByteString
        getEntityClassBytes();

        /**
         * <code>bytes entity = 2;</code>
         */
        com.google.protobuf.ByteString getEntity();
    }

    /**
     * Protobuf type {@code datalayer.model.Entity}
     */
    public static final class Entity extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:datalayer.model.Entity)
            EntityOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use Entity.newBuilder() to construct.
        private Entity(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private Entity() {
            entityClass_ = "";
            entity_ = com.google.protobuf.ByteString.EMPTY;
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        private Entity(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownFieldProto3(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            java.lang.String s = input.readStringRequireUtf8();

                            entityClass_ = s;
                            break;
                        }
                        case 18: {

                            entity_ = input.readBytes();
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return DataLayerProtocol.internal_static_datalayer_model_Entity_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return DataLayerProtocol.internal_static_datalayer_model_Entity_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            DataLayerProtocol.Entity.class, DataLayerProtocol.Entity.Builder.class);
        }

        public static final int ENTITYCLASS_FIELD_NUMBER = 1;
        private volatile java.lang.Object entityClass_;

        /**
         * <code>string entityClass = 1;</code>
         */
        public java.lang.String getEntityClass() {
            java.lang.Object ref = entityClass_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                entityClass_ = s;
                return s;
            }
        }

        /**
         * <code>string entityClass = 1;</code>
         */
        public com.google.protobuf.ByteString
        getEntityClassBytes() {
            java.lang.Object ref = entityClass_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                entityClass_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int ENTITY_FIELD_NUMBER = 2;
        private com.google.protobuf.ByteString entity_;

        /**
         * <code>bytes entity = 2;</code>
         */
        public com.google.protobuf.ByteString getEntity() {
            return entity_;
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (!getEntityClassBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, entityClass_);
            }
            if (!entity_.isEmpty()) {
                output.writeBytes(2, entity_);
            }
            unknownFields.writeTo(output);
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (!getEntityClassBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, entityClass_);
            }
            if (!entity_.isEmpty()) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(2, entity_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof DataLayerProtocol.Entity)) {
                return super.equals(obj);
            }
            DataLayerProtocol.Entity other = (DataLayerProtocol.Entity) obj;

            boolean result = true;
            result = result && getEntityClass()
                    .equals(other.getEntityClass());
            result = result && getEntity()
                    .equals(other.getEntity());
            result = result && unknownFields.equals(other.unknownFields);
            return result;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + ENTITYCLASS_FIELD_NUMBER;
            hash = (53 * hash) + getEntityClass().hashCode();
            hash = (37 * hash) + ENTITY_FIELD_NUMBER;
            hash = (53 * hash) + getEntity().hashCode();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static DataLayerProtocol.Entity parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static DataLayerProtocol.Entity parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static DataLayerProtocol.Entity parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static DataLayerProtocol.Entity parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static DataLayerProtocol.Entity parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static DataLayerProtocol.Entity parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static DataLayerProtocol.Entity parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static DataLayerProtocol.Entity parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static DataLayerProtocol.Entity parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static DataLayerProtocol.Entity parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static DataLayerProtocol.Entity parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static DataLayerProtocol.Entity parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(DataLayerProtocol.Entity prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code datalayer.model.Entity}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:datalayer.model.Entity)
                DataLayerProtocol.EntityOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return DataLayerProtocol.internal_static_datalayer_model_Entity_descriptor;
            }

            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return DataLayerProtocol.internal_static_datalayer_model_Entity_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                DataLayerProtocol.Entity.class, DataLayerProtocol.Entity.Builder.class);
            }

            // Construct using com.nobodyhub.datalayer.core.model.DataLayerProtocol.Entity.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                entityClass_ = "";

                entity_ = com.google.protobuf.ByteString.EMPTY;

                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return DataLayerProtocol.internal_static_datalayer_model_Entity_descriptor;
            }

            public DataLayerProtocol.Entity getDefaultInstanceForType() {
                return DataLayerProtocol.Entity.getDefaultInstance();
            }

            public DataLayerProtocol.Entity build() {
                DataLayerProtocol.Entity result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public DataLayerProtocol.Entity buildPartial() {
                DataLayerProtocol.Entity result = new DataLayerProtocol.Entity(this);
                result.entityClass_ = entityClass_;
                result.entity_ = entity_;
                onBuilt();
                return result;
            }

            public Builder clone() {
                return (Builder) super.clone();
            }

            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return (Builder) super.setField(field, value);
            }

            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }

            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }

            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof DataLayerProtocol.Entity) {
                    return mergeFrom((DataLayerProtocol.Entity) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(DataLayerProtocol.Entity other) {
                if (other == DataLayerProtocol.Entity.getDefaultInstance())
                    return this;
                if (!other.getEntityClass().isEmpty()) {
                    entityClass_ = other.entityClass_;
                    onChanged();
                }
                if (other.getEntity() != com.google.protobuf.ByteString.EMPTY) {
                    setEntity(other.getEntity());
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                DataLayerProtocol.Entity parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (DataLayerProtocol.Entity) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private java.lang.Object entityClass_ = "";

            /**
             * <code>string entityClass = 1;</code>
             */
            public java.lang.String getEntityClass() {
                java.lang.Object ref = entityClass_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    entityClass_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string entityClass = 1;</code>
             */
            public com.google.protobuf.ByteString
            getEntityClassBytes() {
                java.lang.Object ref = entityClass_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    entityClass_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string entityClass = 1;</code>
             */
            public Builder setEntityClass(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                entityClass_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string entityClass = 1;</code>
             */
            public Builder clearEntityClass() {

                entityClass_ = getDefaultInstance().getEntityClass();
                onChanged();
                return this;
            }

            /**
             * <code>string entityClass = 1;</code>
             */
            public Builder setEntityClassBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                entityClass_ = value;
                onChanged();
                return this;
            }

            private com.google.protobuf.ByteString entity_ = com.google.protobuf.ByteString.EMPTY;

            /**
             * <code>bytes entity = 2;</code>
             */
            public com.google.protobuf.ByteString getEntity() {
                return entity_;
            }

            /**
             * <code>bytes entity = 2;</code>
             */
            public Builder setEntity(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                entity_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>bytes entity = 2;</code>
             */
            public Builder clearEntity() {

                entity_ = getDefaultInstance().getEntity();
                onChanged();
                return this;
            }

            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFieldsProto3(unknownFields);
            }

            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:datalayer.model.Entity)
        }

        // @@protoc_insertion_point(class_scope:datalayer.model.Entity)
        private static final DataLayerProtocol.Entity DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new DataLayerProtocol.Entity();
        }

        public static DataLayerProtocol.Entity getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<Entity>
                PARSER = new com.google.protobuf.AbstractParser<Entity>() {
            public Entity parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new Entity(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<Entity> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<Entity> getParserForType() {
            return PARSER;
        }

        public DataLayerProtocol.Entity getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    public interface ReponseOrBuilder extends
            // @@protoc_insertion_point(interface_extends:datalayer.model.Reponse)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>int32 errorCode = 1;</code>
         */
        int getErrorCode();

        /**
         * <code>.datalayer.model.Entity entity = 2;</code>
         */
        boolean hasEntity();

        /**
         * <code>.datalayer.model.Entity entity = 2;</code>
         */
        DataLayerProtocol.Entity getEntity();

        /**
         * <code>.datalayer.model.Entity entity = 2;</code>
         */
        DataLayerProtocol.EntityOrBuilder getEntityOrBuilder();
    }

    /**
     * Protobuf type {@code datalayer.model.Reponse}
     */
    public static final class Reponse extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:datalayer.model.Reponse)
            ReponseOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use Reponse.newBuilder() to construct.
        private Reponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private Reponse() {
            errorCode_ = 0;
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        private Reponse(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownFieldProto3(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 8: {

                            errorCode_ = input.readInt32();
                            break;
                        }
                        case 18: {
                            DataLayerProtocol.Entity.Builder subBuilder = null;
                            if (entity_ != null) {
                                subBuilder = entity_.toBuilder();
                            }
                            entity_ = input.readMessage(DataLayerProtocol.Entity.parser(), extensionRegistry);
                            if (subBuilder != null) {
                                subBuilder.mergeFrom(entity_);
                                entity_ = subBuilder.buildPartial();
                            }

                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return DataLayerProtocol.internal_static_datalayer_model_Reponse_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return DataLayerProtocol.internal_static_datalayer_model_Reponse_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            DataLayerProtocol.Reponse.class, DataLayerProtocol.Reponse.Builder.class);
        }

        public static final int ERRORCODE_FIELD_NUMBER = 1;
        private int errorCode_;

        /**
         * <code>int32 errorCode = 1;</code>
         */
        public int getErrorCode() {
            return errorCode_;
        }

        public static final int ENTITY_FIELD_NUMBER = 2;
        private DataLayerProtocol.Entity entity_;

        /**
         * <code>.datalayer.model.Entity entity = 2;</code>
         */
        public boolean hasEntity() {
            return entity_ != null;
        }

        /**
         * <code>.datalayer.model.Entity entity = 2;</code>
         */
        public DataLayerProtocol.Entity getEntity() {
            return entity_ == null ? DataLayerProtocol.Entity.getDefaultInstance() : entity_;
        }

        /**
         * <code>.datalayer.model.Entity entity = 2;</code>
         */
        public DataLayerProtocol.EntityOrBuilder getEntityOrBuilder() {
            return getEntity();
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (errorCode_ != 0) {
                output.writeInt32(1, errorCode_);
            }
            if (entity_ != null) {
                output.writeMessage(2, getEntity());
            }
            unknownFields.writeTo(output);
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (errorCode_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(1, errorCode_);
            }
            if (entity_ != null) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(2, getEntity());
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof DataLayerProtocol.Reponse)) {
                return super.equals(obj);
            }
            DataLayerProtocol.Reponse other = (DataLayerProtocol.Reponse) obj;

            boolean result = true;
            result = result && (getErrorCode()
                    == other.getErrorCode());
            result = result && (hasEntity() == other.hasEntity());
            if (hasEntity()) {
                result = result && getEntity()
                        .equals(other.getEntity());
            }
            result = result && unknownFields.equals(other.unknownFields);
            return result;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + ERRORCODE_FIELD_NUMBER;
            hash = (53 * hash) + getErrorCode();
            if (hasEntity()) {
                hash = (37 * hash) + ENTITY_FIELD_NUMBER;
                hash = (53 * hash) + getEntity().hashCode();
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static DataLayerProtocol.Reponse parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static DataLayerProtocol.Reponse parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static DataLayerProtocol.Reponse parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static DataLayerProtocol.Reponse parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static DataLayerProtocol.Reponse parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static DataLayerProtocol.Reponse parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static DataLayerProtocol.Reponse parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static DataLayerProtocol.Reponse parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static DataLayerProtocol.Reponse parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static DataLayerProtocol.Reponse parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static DataLayerProtocol.Reponse parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static DataLayerProtocol.Reponse parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(DataLayerProtocol.Reponse prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code datalayer.model.Reponse}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:datalayer.model.Reponse)
                DataLayerProtocol.ReponseOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return DataLayerProtocol.internal_static_datalayer_model_Reponse_descriptor;
            }

            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return DataLayerProtocol.internal_static_datalayer_model_Reponse_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                DataLayerProtocol.Reponse.class, DataLayerProtocol.Reponse.Builder.class);
            }

            // Construct using com.nobodyhub.datalayer.core.model.DataLayerProtocol.Reponse.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                errorCode_ = 0;

                if (entityBuilder_ == null) {
                    entity_ = null;
                } else {
                    entity_ = null;
                    entityBuilder_ = null;
                }
                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return DataLayerProtocol.internal_static_datalayer_model_Reponse_descriptor;
            }

            public DataLayerProtocol.Reponse getDefaultInstanceForType() {
                return DataLayerProtocol.Reponse.getDefaultInstance();
            }

            public DataLayerProtocol.Reponse build() {
                DataLayerProtocol.Reponse result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public DataLayerProtocol.Reponse buildPartial() {
                DataLayerProtocol.Reponse result = new DataLayerProtocol.Reponse(this);
                result.errorCode_ = errorCode_;
                if (entityBuilder_ == null) {
                    result.entity_ = entity_;
                } else {
                    result.entity_ = entityBuilder_.build();
                }
                onBuilt();
                return result;
            }

            public Builder clone() {
                return (Builder) super.clone();
            }

            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return (Builder) super.setField(field, value);
            }

            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }

            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }

            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof DataLayerProtocol.Reponse) {
                    return mergeFrom((DataLayerProtocol.Reponse) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(DataLayerProtocol.Reponse other) {
                if (other == DataLayerProtocol.Reponse.getDefaultInstance())
                    return this;
                if (other.getErrorCode() != 0) {
                    setErrorCode(other.getErrorCode());
                }
                if (other.hasEntity()) {
                    mergeEntity(other.getEntity());
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                DataLayerProtocol.Reponse parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (DataLayerProtocol.Reponse) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int errorCode_;

            /**
             * <code>int32 errorCode = 1;</code>
             */
            public int getErrorCode() {
                return errorCode_;
            }

            /**
             * <code>int32 errorCode = 1;</code>
             */
            public Builder setErrorCode(int value) {

                errorCode_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>int32 errorCode = 1;</code>
             */
            public Builder clearErrorCode() {

                errorCode_ = 0;
                onChanged();
                return this;
            }

            private DataLayerProtocol.Entity entity_ = null;
            private com.google.protobuf.SingleFieldBuilderV3<
                    DataLayerProtocol.Entity, DataLayerProtocol.Entity.Builder, DataLayerProtocol.EntityOrBuilder> entityBuilder_;

            /**
             * <code>.datalayer.model.Entity entity = 2;</code>
             */
            public boolean hasEntity() {
                return entityBuilder_ != null || entity_ != null;
            }

            /**
             * <code>.datalayer.model.Entity entity = 2;</code>
             */
            public DataLayerProtocol.Entity getEntity() {
                if (entityBuilder_ == null) {
                    return entity_ == null ? DataLayerProtocol.Entity.getDefaultInstance() : entity_;
                } else {
                    return entityBuilder_.getMessage();
                }
            }

            /**
             * <code>.datalayer.model.Entity entity = 2;</code>
             */
            public Builder setEntity(DataLayerProtocol.Entity value) {
                if (entityBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    entity_ = value;
                    onChanged();
                } else {
                    entityBuilder_.setMessage(value);
                }

                return this;
            }

            /**
             * <code>.datalayer.model.Entity entity = 2;</code>
             */
            public Builder setEntity(
                    DataLayerProtocol.Entity.Builder builderForValue) {
                if (entityBuilder_ == null) {
                    entity_ = builderForValue.build();
                    onChanged();
                } else {
                    entityBuilder_.setMessage(builderForValue.build());
                }

                return this;
            }

            /**
             * <code>.datalayer.model.Entity entity = 2;</code>
             */
            public Builder mergeEntity(DataLayerProtocol.Entity value) {
                if (entityBuilder_ == null) {
                    if (entity_ != null) {
                        entity_ =
                                DataLayerProtocol.Entity.newBuilder(entity_).mergeFrom(value).buildPartial();
                    } else {
                        entity_ = value;
                    }
                    onChanged();
                } else {
                    entityBuilder_.mergeFrom(value);
                }

                return this;
            }

            /**
             * <code>.datalayer.model.Entity entity = 2;</code>
             */
            public Builder clearEntity() {
                if (entityBuilder_ == null) {
                    entity_ = null;
                    onChanged();
                } else {
                    entity_ = null;
                    entityBuilder_ = null;
                }

                return this;
            }

            /**
             * <code>.datalayer.model.Entity entity = 2;</code>
             */
            public DataLayerProtocol.Entity.Builder getEntityBuilder() {

                onChanged();
                return getEntityFieldBuilder().getBuilder();
            }

            /**
             * <code>.datalayer.model.Entity entity = 2;</code>
             */
            public DataLayerProtocol.EntityOrBuilder getEntityOrBuilder() {
                if (entityBuilder_ != null) {
                    return entityBuilder_.getMessageOrBuilder();
                } else {
                    return entity_ == null ?
                            DataLayerProtocol.Entity.getDefaultInstance() : entity_;
                }
            }

            /**
             * <code>.datalayer.model.Entity entity = 2;</code>
             */
            private com.google.protobuf.SingleFieldBuilderV3<
                    DataLayerProtocol.Entity, DataLayerProtocol.Entity.Builder, DataLayerProtocol.EntityOrBuilder>
            getEntityFieldBuilder() {
                if (entityBuilder_ == null) {
                    entityBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                            DataLayerProtocol.Entity, DataLayerProtocol.Entity.Builder, DataLayerProtocol.EntityOrBuilder>(
                            getEntity(),
                            getParentForChildren(),
                            isClean());
                    entity_ = null;
                }
                return entityBuilder_;
            }

            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFieldsProto3(unknownFields);
            }

            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:datalayer.model.Reponse)
        }

        // @@protoc_insertion_point(class_scope:datalayer.model.Reponse)
        private static final DataLayerProtocol.Reponse DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new DataLayerProtocol.Reponse();
        }

        public static DataLayerProtocol.Reponse getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<Reponse>
                PARSER = new com.google.protobuf.AbstractParser<Reponse>() {
            public Reponse parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new Reponse(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<Reponse> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<Reponse> getParserForType() {
            return PARSER;
        }

        public DataLayerProtocol.Reponse getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    public interface RequestOrBuilder extends
            // @@protoc_insertion_point(interface_extends:datalayer.model.Request)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>.datalayer.model.OpType opType = 1;</code>
         */
        int getOpTypeValue();

        /**
         * <code>.datalayer.model.OpType opType = 1;</code>
         */
        DataLayerProtocol.OpType getOpType();

        /**
         * <code>.datalayer.model.Entity entity = 2;</code>
         */
        boolean hasEntity();

        /**
         * <code>.datalayer.model.Entity entity = 2;</code>
         */
        DataLayerProtocol.Entity getEntity();

        /**
         * <code>.datalayer.model.Entity entity = 2;</code>
         */
        DataLayerProtocol.EntityOrBuilder getEntityOrBuilder();
    }

    /**
     * Protobuf type {@code datalayer.model.Request}
     */
    public static final class Request extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:datalayer.model.Request)
            RequestOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use Request.newBuilder() to construct.
        private Request(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private Request() {
            opType_ = 0;
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        private Request(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownFieldProto3(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 8: {
                            int rawValue = input.readEnum();

                            opType_ = rawValue;
                            break;
                        }
                        case 18: {
                            DataLayerProtocol.Entity.Builder subBuilder = null;
                            if (entity_ != null) {
                                subBuilder = entity_.toBuilder();
                            }
                            entity_ = input.readMessage(DataLayerProtocol.Entity.parser(), extensionRegistry);
                            if (subBuilder != null) {
                                subBuilder.mergeFrom(entity_);
                                entity_ = subBuilder.buildPartial();
                            }

                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return DataLayerProtocol.internal_static_datalayer_model_Request_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return DataLayerProtocol.internal_static_datalayer_model_Request_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            DataLayerProtocol.Request.class, DataLayerProtocol.Request.Builder.class);
        }

        public static final int OPTYPE_FIELD_NUMBER = 1;
        private int opType_;

        /**
         * <code>.datalayer.model.OpType opType = 1;</code>
         */
        public int getOpTypeValue() {
            return opType_;
        }

        /**
         * <code>.datalayer.model.OpType opType = 1;</code>
         */
        public DataLayerProtocol.OpType getOpType() {
            DataLayerProtocol.OpType result = DataLayerProtocol.OpType.valueOf(opType_);
            return result == null ? DataLayerProtocol.OpType.UNRECOGNIZED : result;
        }

        public static final int ENTITY_FIELD_NUMBER = 2;
        private DataLayerProtocol.Entity entity_;

        /**
         * <code>.datalayer.model.Entity entity = 2;</code>
         */
        public boolean hasEntity() {
            return entity_ != null;
        }

        /**
         * <code>.datalayer.model.Entity entity = 2;</code>
         */
        public DataLayerProtocol.Entity getEntity() {
            return entity_ == null ? DataLayerProtocol.Entity.getDefaultInstance() : entity_;
        }

        /**
         * <code>.datalayer.model.Entity entity = 2;</code>
         */
        public DataLayerProtocol.EntityOrBuilder getEntityOrBuilder() {
            return getEntity();
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (opType_ != DataLayerProtocol.OpType.CREATE.getNumber()) {
                output.writeEnum(1, opType_);
            }
            if (entity_ != null) {
                output.writeMessage(2, getEntity());
            }
            unknownFields.writeTo(output);
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (opType_ != DataLayerProtocol.OpType.CREATE.getNumber()) {
                size += com.google.protobuf.CodedOutputStream
                        .computeEnumSize(1, opType_);
            }
            if (entity_ != null) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(2, getEntity());
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof DataLayerProtocol.Request)) {
                return super.equals(obj);
            }
            DataLayerProtocol.Request other = (DataLayerProtocol.Request) obj;

            boolean result = true;
            result = result && opType_ == other.opType_;
            result = result && (hasEntity() == other.hasEntity());
            if (hasEntity()) {
                result = result && getEntity()
                        .equals(other.getEntity());
            }
            result = result && unknownFields.equals(other.unknownFields);
            return result;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + OPTYPE_FIELD_NUMBER;
            hash = (53 * hash) + opType_;
            if (hasEntity()) {
                hash = (37 * hash) + ENTITY_FIELD_NUMBER;
                hash = (53 * hash) + getEntity().hashCode();
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static DataLayerProtocol.Request parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static DataLayerProtocol.Request parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static DataLayerProtocol.Request parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static DataLayerProtocol.Request parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static DataLayerProtocol.Request parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static DataLayerProtocol.Request parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static DataLayerProtocol.Request parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static DataLayerProtocol.Request parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static DataLayerProtocol.Request parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static DataLayerProtocol.Request parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static DataLayerProtocol.Request parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static DataLayerProtocol.Request parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(DataLayerProtocol.Request prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code datalayer.model.Request}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:datalayer.model.Request)
                DataLayerProtocol.RequestOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return DataLayerProtocol.internal_static_datalayer_model_Request_descriptor;
            }

            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return DataLayerProtocol.internal_static_datalayer_model_Request_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                DataLayerProtocol.Request.class, DataLayerProtocol.Request.Builder.class);
            }

            // Construct using com.nobodyhub.datalayer.core.model.DataLayerProtocol.Request.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                opType_ = 0;

                if (entityBuilder_ == null) {
                    entity_ = null;
                } else {
                    entity_ = null;
                    entityBuilder_ = null;
                }
                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return DataLayerProtocol.internal_static_datalayer_model_Request_descriptor;
            }

            public DataLayerProtocol.Request getDefaultInstanceForType() {
                return DataLayerProtocol.Request.getDefaultInstance();
            }

            public DataLayerProtocol.Request build() {
                DataLayerProtocol.Request result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public DataLayerProtocol.Request buildPartial() {
                DataLayerProtocol.Request result = new DataLayerProtocol.Request(this);
                result.opType_ = opType_;
                if (entityBuilder_ == null) {
                    result.entity_ = entity_;
                } else {
                    result.entity_ = entityBuilder_.build();
                }
                onBuilt();
                return result;
            }

            public Builder clone() {
                return (Builder) super.clone();
            }

            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return (Builder) super.setField(field, value);
            }

            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }

            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }

            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof DataLayerProtocol.Request) {
                    return mergeFrom((DataLayerProtocol.Request) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(DataLayerProtocol.Request other) {
                if (other == DataLayerProtocol.Request.getDefaultInstance())
                    return this;
                if (other.opType_ != 0) {
                    setOpTypeValue(other.getOpTypeValue());
                }
                if (other.hasEntity()) {
                    mergeEntity(other.getEntity());
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                DataLayerProtocol.Request parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (DataLayerProtocol.Request) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int opType_ = 0;

            /**
             * <code>.datalayer.model.OpType opType = 1;</code>
             */
            public int getOpTypeValue() {
                return opType_;
            }

            /**
             * <code>.datalayer.model.OpType opType = 1;</code>
             */
            public Builder setOpTypeValue(int value) {
                opType_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>.datalayer.model.OpType opType = 1;</code>
             */
            public DataLayerProtocol.OpType getOpType() {
                DataLayerProtocol.OpType result = DataLayerProtocol.OpType.valueOf(opType_);
                return result == null ? DataLayerProtocol.OpType.UNRECOGNIZED : result;
            }

            /**
             * <code>.datalayer.model.OpType opType = 1;</code>
             */
            public Builder setOpType(DataLayerProtocol.OpType value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                opType_ = value.getNumber();
                onChanged();
                return this;
            }

            /**
             * <code>.datalayer.model.OpType opType = 1;</code>
             */
            public Builder clearOpType() {

                opType_ = 0;
                onChanged();
                return this;
            }

            private DataLayerProtocol.Entity entity_ = null;
            private com.google.protobuf.SingleFieldBuilderV3<
                    DataLayerProtocol.Entity, DataLayerProtocol.Entity.Builder, DataLayerProtocol.EntityOrBuilder> entityBuilder_;

            /**
             * <code>.datalayer.model.Entity entity = 2;</code>
             */
            public boolean hasEntity() {
                return entityBuilder_ != null || entity_ != null;
            }

            /**
             * <code>.datalayer.model.Entity entity = 2;</code>
             */
            public DataLayerProtocol.Entity getEntity() {
                if (entityBuilder_ == null) {
                    return entity_ == null ? DataLayerProtocol.Entity.getDefaultInstance() : entity_;
                } else {
                    return entityBuilder_.getMessage();
                }
            }

            /**
             * <code>.datalayer.model.Entity entity = 2;</code>
             */
            public Builder setEntity(DataLayerProtocol.Entity value) {
                if (entityBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    entity_ = value;
                    onChanged();
                } else {
                    entityBuilder_.setMessage(value);
                }

                return this;
            }

            /**
             * <code>.datalayer.model.Entity entity = 2;</code>
             */
            public Builder setEntity(
                    DataLayerProtocol.Entity.Builder builderForValue) {
                if (entityBuilder_ == null) {
                    entity_ = builderForValue.build();
                    onChanged();
                } else {
                    entityBuilder_.setMessage(builderForValue.build());
                }

                return this;
            }

            /**
             * <code>.datalayer.model.Entity entity = 2;</code>
             */
            public Builder mergeEntity(DataLayerProtocol.Entity value) {
                if (entityBuilder_ == null) {
                    if (entity_ != null) {
                        entity_ =
                                DataLayerProtocol.Entity.newBuilder(entity_).mergeFrom(value).buildPartial();
                    } else {
                        entity_ = value;
                    }
                    onChanged();
                } else {
                    entityBuilder_.mergeFrom(value);
                }

                return this;
            }

            /**
             * <code>.datalayer.model.Entity entity = 2;</code>
             */
            public Builder clearEntity() {
                if (entityBuilder_ == null) {
                    entity_ = null;
                    onChanged();
                } else {
                    entity_ = null;
                    entityBuilder_ = null;
                }

                return this;
            }

            /**
             * <code>.datalayer.model.Entity entity = 2;</code>
             */
            public DataLayerProtocol.Entity.Builder getEntityBuilder() {

                onChanged();
                return getEntityFieldBuilder().getBuilder();
            }

            /**
             * <code>.datalayer.model.Entity entity = 2;</code>
             */
            public DataLayerProtocol.EntityOrBuilder getEntityOrBuilder() {
                if (entityBuilder_ != null) {
                    return entityBuilder_.getMessageOrBuilder();
                } else {
                    return entity_ == null ?
                            DataLayerProtocol.Entity.getDefaultInstance() : entity_;
                }
            }

            /**
             * <code>.datalayer.model.Entity entity = 2;</code>
             */
            private com.google.protobuf.SingleFieldBuilderV3<
                    DataLayerProtocol.Entity, DataLayerProtocol.Entity.Builder, DataLayerProtocol.EntityOrBuilder>
            getEntityFieldBuilder() {
                if (entityBuilder_ == null) {
                    entityBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                            DataLayerProtocol.Entity, DataLayerProtocol.Entity.Builder, DataLayerProtocol.EntityOrBuilder>(
                            getEntity(),
                            getParentForChildren(),
                            isClean());
                    entity_ = null;
                }
                return entityBuilder_;
            }

            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFieldsProto3(unknownFields);
            }

            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:datalayer.model.Request)
        }

        // @@protoc_insertion_point(class_scope:datalayer.model.Request)
        private static final DataLayerProtocol.Request DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new DataLayerProtocol.Request();
        }

        public static DataLayerProtocol.Request getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<Request>
                PARSER = new com.google.protobuf.AbstractParser<Request>() {
            public Request parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new Request(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<Request> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<Request> getParserForType() {
            return PARSER;
        }

        public DataLayerProtocol.Request getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_datalayer_model_Entity_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_datalayer_model_Entity_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_datalayer_model_Reponse_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_datalayer_model_Reponse_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_datalayer_model_Request_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_datalayer_model_Request_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\020data-layer.proto\022\017datalayer.model\"-\n\006E" +
                        "ntity\022\023\n\013entityClass\030\001 \001(\t\022\016\n\006entity\030\002 \001" +
                        "(\014\"E\n\007Reponse\022\021\n\terrorCode\030\001 \001(\005\022\'\n\006enti" +
                        "ty\030\002 \001(\0132\027.datalayer.model.Entity\"[\n\007Req" +
                        "uest\022\'\n\006opType\030\001 \001(\0162\027.datalayer.model.O" +
                        "pType\022\'\n\006entity\030\002 \001(\0132\027.datalayer.model." +
                        "Entity*6\n\006OpType\022\n\n\006CREATE\020\000\022\010\n\004RRED\020\001\022\n" +
                        "\n\006UPDATE\020\002\022\n\n\006DELETE\020\0032S\n\020DataLayerServi" +
                        "ce\022?\n\007execute\022\030.datalayer.model.Request\032" +
                        "\030.datalayer.model.Reponse(\001B7\n\"com.nobod" +
                        "yhub.datalayer.core.modelB\021DataLayerProt" +
                        "ocolb\006proto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        }, assigner);
        internal_static_datalayer_model_Entity_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_datalayer_model_Entity_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_datalayer_model_Entity_descriptor,
                new java.lang.String[]{"EntityClass", "Entity",});
        internal_static_datalayer_model_Reponse_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_datalayer_model_Reponse_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_datalayer_model_Reponse_descriptor,
                new java.lang.String[]{"ErrorCode", "Entity",});
        internal_static_datalayer_model_Request_descriptor =
                getDescriptor().getMessageTypes().get(2);
        internal_static_datalayer_model_Request_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_datalayer_model_Request_descriptor,
                new java.lang.String[]{"OpType", "Entity",});
    }

    // @@protoc_insertion_point(outer_class_scope)
}
