create table User (id integer generated by default as identity, email varchar(255), firstName varchar(255), lastName varchar(255), password varchar(255), primary key (id));

INSERT INTO User(email,firstName,lastName,password) VALUES ('admin@admin.com','admin','admin','admin');

INSERT INTO User(email,firstName,lastName,password) VALUES ('john@gmail.com','john','doe','johndoe');

INSERT INTO User(email,firstName,lastName,password) VALUES ('sham@yahoo.com','sham','tis','shamtis');